import { Theme } from '#/types/theme';

import { COLORS, FONT_SIZES, FONT_WEIGHTS, FONTS } from './styles';

export const THEME: Theme = {
    colors: {
        datepickerBorder: COLORS.gainsboro,
        datepickerBg: COLORS.white,
        datepickerFg: COLORS.darkCharcoal,
        datepickerPlaceholder: COLORS.grayX11,
        datepickerLabelFg: COLORS.darkCharcoal,
        calendarBorder: COLORS.chineseWhite,
        calendarBg: COLORS.white,
        calendarFg: COLORS.darkCharcoal,
        calendarSliderBg: COLORS.white,
        calendarSliderFg: COLORS.darkCharcoal,
        calendarSliderHoverBg: COLORS.antiFlashWhite,
        calendarSliderHoverFg: COLORS.darkCharcoal,
        calendarTitleCellBg: COLORS.white,
        calendarTitleCellFg: COLORS.darkCharcoal,
        calendarTitleCellHoverBg: COLORS.white,
        calendarTitleCellHoverFg: COLORS.darkCharcoal,
        calendarCellBg: COLORS.white,
        calendarCellFg: COLORS.darkCharcoal,
        calendarCellHoverBg: COLORS.antiFlashWhite,
        calendarCellHoverFg: COLORS.darkCharcoal,
        calendarCellDisabledBg: COLORS.white,
        calendarCellDisabledFg: COLORS.darkGrayX11,
        calendarCellSelectedBg: COLORS.bleuDeFrance,
        calendarCellSelectedFg: COLORS.white,
        calendarCellRangeStartBg: COLORS.bleuDeFrance60P,
        calendarCellRangeStartFg: COLORS.white,
        calendarCellRangeMiddleBg: COLORS.bleuDeFrance10P,
        calendarCellRangeMiddleFg: COLORS.bleuDeFrance,
        calendarCellRangeEndBg: COLORS.bleuDeFrance,
        calendarCellRangeEndFg: COLORS.white,
        calendarCellWeekendBg: COLORS.white,
        calendarCellWeekendFg: COLORS.internationalOrange,
        calendarCellHolidayBg: COLORS.white,
        calendarCellHolidayFg: COLORS.tennesseeOrange,
        calendarCellTodoMarker: COLORS.tennesseeOrange,
        calendarButtonBorder: COLORS.chineseWhite,
        calendarButtonBg: COLORS.white,
        calendarButtonFg: COLORS.darkCharcoal,
        calendarButtonHoverBg: COLORS.antiFlashWhite,
        calendarButtonHoverFg: COLORS.darkCharcoal,
    },
    fonts: {
        datepicker: FONTS.openSans,
        calendar: FONTS.openSans,
    },
    fontSizes: {
        datepicker: FONT_SIZES.xl,
        datepickerLable: FONT_SIZES.xl,
        calendar: FONT_SIZES.xl,
        calendarSlider: FONT_SIZES.l,
        calendarTitleCell: FONT_SIZES.l,
        calendarCell: FONT_SIZES.m,
        calendarButton: FONT_SIZES.s,
    },
    fontWeights: {
        datepicker: FONT_WEIGHTS.s,
        datepickerLable: FONT_WEIGHTS.m,
        calendar: FONT_WEIGHTS.s,
        calendarSlider: FONT_WEIGHTS.l,
        calendarTitleCell: FONT_WEIGHTS.l,
        calendarCell: FONT_WEIGHTS.m,
        calendarButton: FONT_WEIGHTS.m,
    },
};
